"""empty message

Revision ID: 7a059b5a65f8
Revises: ec1fe3a3fcb9
Create Date: 2019-05-16 19:01:09.570199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a059b5a65f8'
down_revision = 'ec1fe3a3fcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clerks', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint(u'clerks_org_id_fkey', 'clerks', type_='foreignkey')
    op.create_foreign_key(None, 'clerks', 'organizations', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('clerks', 'org_id')
    op.create_foreign_key(None, 'customers', 'organizations', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.add_column('clerks', sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clerks', type_='foreignkey')
    op.create_foreign_key(u'clerks_org_id_fkey', 'clerks', 'organizations', ['org_id'], ['id'], ondelete=u'CASCADE')
    op.drop_column('clerks', 'id')
    # ### end Alembic commands ###
