"""empty message

Revision ID: ec1fe3a3fcb9
Revises: be21b2c45143
Create Date: 2019-05-16 18:59:41.841760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1fe3a3fcb9'
down_revision = 'be21b2c45143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clerks', sa.Column('org_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clerks', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clerks', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clerks', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'clerks', type_='foreignkey')
    op.drop_column('clerks', 'org_id')
    # ### end Alembic commands ###
